CREATE TABLE TipoVia (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo VARCHAR(50) NOT NULL,
    codigo VARCHAR(10) NOT NULL,
    abreviatura VARCHAR(10),
    descripcion VARCHAR(255),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Via (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    longitud DOUBLE NOT NULL,
    ancho DOUBLE NOT NULL,
    capacidad INT NOT NULL,
    estado VARCHAR(255) NOT NULL,
    congestion VARCHAR(255) NOT NULL,
    tipo_id BIGINT,
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_TipoVia FOREIGN KEY (tipo_id) REFERENCES TipoVia(id) ON DELETE SET NULL
);